#!/usr/bin/env bash

command_not_found_handle() {
   echo "--- $1 ----"
   if [ -f "$1" ]; then
      pypy3 $@
   else
      >&2 echo "$@ command missing"
      return 1
   fi
}

reload() {
  . $Ell/ellrc
}

here() { cd $1; basename `pwd`; }

doc() { pycco -d $Ell $1; }

alias gg="git pull"
alias gs="git status"
alias gp="git commit -am 'saving'; git push; git status"

PROMPT_COMMAND='echo -ne "DUO:$(git branch 2>/dev/null | grep '^*' | colrm 1 2) ";PS1="$(here ..)/$(here .) \!>\e[m "'

