#!/usr/bin/env bash

Ish=$(dirname $(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd ))
chmod +x $Ish/etc/ish
chmod +x $Ish/src/*.py
chmod +x $Ish/src/*.sh
mkdir -p $Ish/docs

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias vi='vim -u $Ish/etc/dotvimrc'
alias tmux='tmux -f $Ish/etc/dottmux'
alias pdoc="pdoc3 --config sort_identifiers=False --template-dir $Ish/docs -o $Ish/docs --force --html "

p() { f=$1; shift; python3 $f.py $*; }

htmls()  { 
   (cd $Ish/duo2; for py in *.py; do pdoc $py; done); 
   git add $Ish/docs/*.html
}

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "‼️  $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
